using System.Data;
using System.Reflection;

using Bss.Platform.Events.Abstractions;
using Bss.Platform.Events.Interfaces;
using Bss.Platform.Events.Models;
using Bss.Platform.Events.Publishers;

using DotNetCore.CAP;
using DotNetCore.CAP.Internal;
using DotNetCore.CAP.Messages;

using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.Filters;
using Microsoft.Extensions.DependencyInjection;

using Savorboard.CAP.InMemoryMessageQueue;

namespace Bss.Platform.Events;

public static class DependencyInjection
{
    public static IServiceCollection AddPlatformDomainEvents(this IServiceCollection services) =>
        services.AddScoped<IDomainEventPublisher, DomainEventPublisher>();

    public static IServiceCollection AddPlatformIntegrationEvents<TEventProcessor>(
        this IServiceCollection services,
        Assembly eventsAssembly,
        Action<IntegrationEventsOptions>? setup = null)
        where TEventProcessor : class, IIntegrationEventProcessor
    {
        services
            .AddSingleton<IIntegrationEventProcessor, TEventProcessor>()
            .AddSingleton<IConsumerServiceSelector, CapConsumerServiceSelectorLegacy>(x => new(x, eventsAssembly))
            .AddScoped<IIntegrationEventPublisher, IntegrationEventPublisherLegacy>()
            .AddPlatformIntegrationEventsInternal(setup);

        return services;
    }

    /// <summary>
    /// A new way to register integration events, required to set up internal and external events
    /// </summary>
    /// <returns>Automatically registered IIntegrationEventPublisher&lt;TEvent&gt; wrap it if you need</returns>
    public static IServiceCollection AddPlatformIntegrationEvents<TEventProcessor, TEvent>(
        this IServiceCollection services,
        Action<IIntegrationEventSetup<TEvent>> setupEvents,
        Action<IntegrationEventsOptions>? setupOptions = null)
        where TEventProcessor : class, IIntegrationEventProcessor<TEvent>
        where TEvent : notnull
    {
        var typeProvider = new EventTypeProvider<TEvent>();
        setupEvents.Invoke(typeProvider);

        services
            .AddSingleton<IEventTypeProvider>(typeProvider)
            .AddSingleton<IConsumerServiceSelector, CapConsumerServiceSelectorNew>()
            .AddScoped<IIntegrationEventPublisher<TEvent>, IntegrationEventPublisherNew<TEvent>>()
            .AddPlatformIntegrationEventsInternal(setupOptions)
            .Configure((RabbitMQOptions opt) =>
            {
                // note: required for messages generated by not CAP
                opt.CustomHeadersBuilder = (msg, sp) =>
                [
                    new(Headers.MessageId, sp.GetRequiredService<ISnowflakeId>().NextId().ToString()),
                    new(Headers.MessageName, msg.RoutingKey),
                    new(Headers.Type, typeof(TEvent).Name)
                ];
            });

        services.AddSingleton<IIntegrationEventProcessor<TEvent>, TEventProcessor>();
        // NOTE: register TEventProcessor for each type (required for CapConsumerExecutor<TEvent>)
        typeProvider.InternalEvents.Keys
            .Select(t => typeof(IIntegrationEventProcessor<>).MakeGenericType(t))
            .ToList()
            .ForEach(x => services.AddSingleton(x, sp => sp.GetRequiredService<IIntegrationEventProcessor<TEvent>>()));

        return services;
    }

    private static IServiceCollection AddPlatformIntegrationEventsInternal(
        this IServiceCollection services,
        Action<IntegrationEventsOptions>? setupEventOptions = null)
    {
        services
            .AddScoped<ICapTransaction>(serviceProvider =>
            {
                var capTransaction = ActivatorUtilities.CreateInstance<SqlServerCapTransaction>(serviceProvider);
                capTransaction.DbTransaction = serviceProvider.GetRequiredService<IDbTransaction>();
                return capTransaction;
            })
            .AddCap(x =>
            {
                var eventsOptions = IntegrationEventsOptions.Default;
                setupEventOptions?.Invoke(eventsOptions);

                x.FailedRetryCount = eventsOptions.FailedRetryCount;
                x.SucceedMessageExpiredAfter = (int)TimeSpan.FromDays(eventsOptions.RetentionDays).TotalSeconds;

                x.UseSqlServer(o =>
                {
                    o.ConnectionString = eventsOptions.SqlServer.ConnectionString;
                    o.Schema = eventsOptions.SqlServer.Schema;
                });

                x.UseDashboard(o =>
                {
                    o.PathMatch = eventsOptions.DashboardPath;
                    if (eventsOptions.AuthorizationPredicate is { } authPredicate)
                    {
                        o.AllowAnonymousExplicit = false;
                        o.AuthorizationPolicy = AddDashboardAuthorizationPolicy(services, authPredicate);
                    }
                });

                var rabbitSettings = eventsOptions.MessageQueue;
                if (!rabbitSettings.Enable)
                {
                    x.UseInMemoryMessageQueue();
                    return;
                }

                x.DefaultGroupName = string.IsNullOrWhiteSpace(rabbitSettings.QueueName)
                    ? rabbitSettings.ExchangeName
                    : rabbitSettings.QueueName;

                x.UseRabbitMQ(o =>
                {
                    o.HostName = rabbitSettings.Host;
                    o.Port = rabbitSettings.Port;
                    o.VirtualHost = rabbitSettings.VirtualHost;
                    o.Password = rabbitSettings.Secret;
                    o.UserName = rabbitSettings.UserName;
                    o.ExchangeName = rabbitSettings.ExchangeName;
                    o.BasicQosOptions = new(1, true);
                });
            });

        return services;
    }

    private static string AddDashboardAuthorizationPolicy(IServiceCollection services, Func<HttpContext, Task<bool>> authPredicate)
    {
        const string policyName = "bss-platform-dashboard-auth";
        services.AddAuthorizationBuilder()
            .AddPolicy(
                policyName,
                policy => policy.RequireAssertion(ctx =>
                {
                    var httpContext = ctx.Resource as HttpContext
                                      ?? (ctx.Resource as AuthorizationFilterContext)?.HttpContext
                                      ?? throw new("Can't authorize, http context is not available");

                    return authPredicate(httpContext);
                }));

        return policyName;
    }
}
